//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.Generation.Roslyn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Code.Generation.Roslyn.StringLiterals", typeof(StringLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define commands if global options or parameters exist..
        /// </summary>
        internal static string CannotDefineCommandsIfArgumentsExist {
            get {
                return ResourceManager.GetString("CannotDefineCommandsIfArgumentsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define multiple parameter lists..
        /// </summary>
        internal static string CannotDefineMultipleParameterLists {
            get {
                return ResourceManager.GetString("CannotDefineMultipleParameterLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; isn&apos;t valid for {1}: {2}.
        /// </summary>
        internal static string CannotParseValueFormat {
            get {
                return ResourceManager.GetString("CannotParseValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string CommandAlreadyDefinedFormat {
            get {
                return ResourceManager.GetString("CommandAlreadyDefinedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; cannot be used for a command..
        /// </summary>
        internal static string CommandNameIsNotValidFormat {
            get {
                return ResourceManager.GetString("CommandNameIsNotValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error: {0}.
        /// </summary>
        internal static string ErrorWithMessageFormat {
            get {
                return ResourceManager.GetString("ErrorWithMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra parameter &apos;{0}&apos;.
        /// </summary>
        internal static string ExtraParameterFormat {
            get {
                return ResourceManager.GetString("ExtraParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: {0}.
        /// </summary>
        internal static string HelpUsageOfApplicationFormat {
            get {
                return ResourceManager.GetString("HelpUsageOfApplicationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid option {0}.
        /// </summary>
        internal static string InvalidOptionFormat {
            get {
                return ResourceManager.GetString("InvalidOptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing command.
        /// </summary>
        internal static string MissingCommand {
            get {
                return ResourceManager.GetString("MissingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a name..
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string OptionAlreadyDefinedFormat {
            get {
                return ResourceManager.GetString("OptionAlreadyDefinedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; cannot be used for an option..
        /// </summary>
        internal static string OptionNameIsNotValidFormat {
            get {
                return ResourceManager.GetString("OptionNameIsNotValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option {0} requires a value.
        /// </summary>
        internal static string OptionRequiresValueFormat {
            get {
                return ResourceManager.GetString("OptionRequiresValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options must be defined before any parameters..
        /// </summary>
        internal static string OptionsMustBeDefinedBeforeParameters {
            get {
                return ResourceManager.GetString("OptionsMustBeDefinedBeforeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string ParameterAlreadyDefinedFormat {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefinedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; cannot be used for a parameter..
        /// </summary>
        internal static string ParameterNameIsNotValidFormat {
            get {
                return ResourceManager.GetString("ParameterNameIsNotValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters cannot be defined after parameter lists..
        /// </summary>
        internal static string ParametersCannotBeDefinedAfterLists {
            get {
                return ResourceManager.GetString("ParametersCannotBeDefinedAfterLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response file &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string ResponseFileDoesNotExistFormat {
            get {
                return ResourceManager.GetString("ResponseFileDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown command &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownCommandFormat {
            get {
                return ResourceManager.GetString("UnknownCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched quote at position {0}..
        /// </summary>
        internal static string UnmatchedQuoteFormat {
            get {
                return ResourceManager.GetString("UnmatchedQuoteFormat", resourceCulture);
            }
        }
    }
}
